fos_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
            - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link','Format','Font','FontSize'] }
            - { name: 'clipboard',   items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] }
            - { name: 'colors',      items: [ 'TextColor','BGColor' ] }
            - { name: 'tools',       items: [ 'Maximize', 'ShowBlocks' ] }
            - { name: 'editing',     items : [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ] }
            - { name: 'document',    items : [ 'Source','-','NewPage','Preview' ] }
