fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: front
    user_class: App\Entity\User
    from_email:
        address: "contact@dev.fr"
        sender_name: "contact_info"