liip_imagine:
  filter_sets:
    home_slider:
      filters:
        thumbnail:
          # set the thumbnail size to "32x32" pixels
          size: [323, 200]
          mode: outbound

    detail_slider:
      filters:
        crop:
          # set the thumbnail size to "32x32" pixels
          size: [768, 274]
          #mode: outbound
    bo_thumb:
      filters:
        thumbnail:
          # set the thumbnail size to "32x32" pixels
          size: [323, 200]
          mode: outbound
    cartouche:
      filters:
        thumbnail:
          size: [281,40]
          mode: outbount